### ISSUE TITLE
Drive – `@odata.type` in request body causing request to fail

### ISSUE THREAD

**Issue by hubipe** [microsoftgraph/msgraph-sdk-php#1006] opened 2022-09-23 09:40 UTC
Hi,
since 2.0.0-RC6 creating upload session stopped to work. Here is a code sample, which used to work until RC5:

```php
use Microsoft\Graph\Generated\Drives\Item\Items\Item\CreateUploadSession\CreateUploadSessionPostRequestBody;
use Microsoft\Graph\Generated\Models\DriveItemUploadableProperties;

$itemProperties = new DriveItemUploadableProperties();
$itemProperties->setAdditionalData([
	'@microsoft.graph.conflictBehavior' => 'replace',
]);

$body = new CreateUploadSessionPostRequestBody();
$body->setItem($itemProperties);

$session = $graph->drivesById($driveId)
	->itemsById('root:/test-file.pdf:')
	->createUploadSession()
	->post($body)
	->wait();
```

The graph API returns HTTP 400 Bad Request.

The problem is within a body of the request. Until the RC5, the request body was:

```json
{
    "item": {
        "@microsoft.graph.conflictBehavior":"replace"
    }
}
```

![image](https://user-images.githubusercontent.com/617880/191933594-ab82a533-b4d0-43bd-ae9d-b45c64450ccd.png)

but since RC6 the request body is:

```json
{
    "item": {
        "@odata.type": "#microsoft.graph.driveItemUploadableProperties",
        "@microsoft.graph.conflictBehavior": "replace"
    }
}
```

![image](https://user-images.githubusercontent.com/617880/191933689-4deccd25-2f7d-40f9-87af-d44df78fb6c7.png)

It seems, that Graph API does not understand the @odata.type item property. Is it necessary to include the @odata.type property?

**Comment by Ndiritu** [comment] 2022-10-27 11:50
@baywet was able to reproduce this bug. `@odata.type` seems to be the cause of failure here. We're also submitting it in every other request payload.

Thinking we shouldn't be adding `@odata.type` in request payloads (via serialize()).
Your thoughts?

**Comment by baywet** [comment] 2022-10-27 12:08
This is a tough problem since OData type support across the service is inconsistent and a lot of workloads don't conform to OData standard requirements.

On one hand the standard [states that services MUST NOT require clients to understand annotations](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_OData40MinimalConformanceLevel). On the other [it state the service MUST handle odata type annotations](http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_Conformance). Lastly, some scenarios are not possible without providing the odata type (e.g. creating a derived type instance in a base type collection, the service wouldn't know what you're sending).

In practice, services do it badly, and in the past our SDKs didn't have a proper implementation either. Such services include Todo, ODSP, etc...
@andrueastman spent a lot of time investigating this before the kiota era. And I believe the conclusion at the time was "always set the OData type, and for services that don't understand it, unset it manually". We can always funnel feedback to the workloads so they fix their implementations.

The workaround here is simple, just unset the odata type before sending the payload so something like:

(excuse my PHP, I haven't written any since PHP4....)

```php
$itemProperties->setOdataType(null)
```

**Comment by baywet** [comment] 2022-10-27 19:45
Thanks for the additional context. Can you expand a bit more on the scenarios when it was set? I think this is something we'll need to tackle in the conversion library.
Was the information set on a per endpoint basis or per entity type basis?

**Comment by baywet** [comment] 2022-10-31 15:34
Thanks for the additional context here. From what I understand this is not "endpoint specific" but a "model specific" aspect which could be addressed in the conversion process.
I'd rather have it being addressed in the conversion step for the following reasons:
- We're not the only ones to use the conversion lib/description, fixing it there would benefit others.
- The cost would only be at conversion time and not at runtime.

Before we make a decision on that, do we have cases for the same type (e.g. user) where setting the odata type works for some endpoints but doesn't for others?

**Comment by andrueastman** [comment] 2022-11-01 08:11
> Before we make a decision on that, do we have cases for the same type (e.g. user) where setting the odata type works for some endpoints but doesn't for others?

As far as I remember, we did not have an issue where the property was needed in one endpoint and caused issues elsewhere. 
The property is set when we detect a need to disambiguate the type when the metadata is generalized due to specifying a base type and we are sending a derived type.

**Comment by andrueastman** [comment] 2022-11-02 08:43
Created https://github.com/microsoft/OpenAPI.NET.OData/issues/304 to track this.

**Comment by hubipe** [comment] 2023-01-13 07:41
Hi all,
I just wanted you to know, that since 2.0.0-RC12 the code works again without modifications. I'm not 100% sure what has changed since RC11, but the @odata.type annotation is not in the request since then.

So maybe this issue could be resolved?

**Comment by Ndiritu** [comment] 2023-01-13 10:52
Thanks for validating this @hubipe.
What's changed is that we are no longer [setting a default value for the OData type](https://github.com/microsoftgraph/msgraph-sdk-php/blob/2.0.0-RC11/src/Generated/Models/DriveItemUploadableProperties.php#L47)

**Closed by Ndiritu** 2023-01-13 10:52 UTC
Labels: bug, v2: feedback
