### ISSUE TITLE
example for attachments/createUploadSession

### ISSUE THREAD

**Issue by KodaCHC** [microsoftgraph/msgraph-sdk-php#1079] opened 2022-11-29 08:54 UTC
I can't reopen an issue. So here is a new one from this (https://github.com/microsoftgraph/msgraph-sdk-php/issues/1047#issuecomment-1300176868)

Have you me an example to use createUploadSession?

My mailbody currently has the following structure for the file attachments
```
$attachmentList[] = [
    "@odata.type" => "#microsoft.graph.fileAttachment",
    "name" => $attachment->getTitle(),
    "contentType" => $attachment->fileType,
    "contentBytes" => \base64_encode(\file_get_contents($attachment->getLocation()))
];
```

And send the email after that:

```
$graph->createRequest("POST", "/users/" . $user . "/sendMail")
     ->attachBody($mailBody)
     ->execute();
```

But for "attachments/createUploadSession" I need a messageId. But before I send my message I don't have a messageId?

**Comment by Ndiritu** [comment] 2022-11-29 10:02
closed as duplicate of #1047

**Closed by Ndiritu** 2022-11-29 10:02 UTC
Labels: ToTriage
