### ISSUE TITLE
Move all pipelines from travis to Azure Pipelines

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php#409] opened 2021-03-04 15:44 UTC
[AB#8442](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8442)

**Comment by Ndiritu** [comment] 2021-05-18 09:45
Duplicate of #409

**Closed by Ndiritu** 2021-05-18 09:45 UTC
